"""refunds_reversal_paidnote

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-16 17:30:24.481689
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('out_refund_no', sa.String(length=64), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('status', sa.Enum('requested', 'success', 'failed', name='refund_status', native_enum=False, length=24), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('out_refund_no')
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    # 存量行的默认值:老入账全部是正常入账(earning),备注为空
    op.add_column('merchant_earnings', sa.Column('kind', sa.Enum('earning', 'reversal', name='earning_kind', native_enum=False, length=24), nullable=False, server_default='earning'))
    op.add_column('merchant_earnings', sa.Column('note', sa.String(length=200), nullable=False, server_default=''))
    op.drop_constraint(op.f('merchant_earnings_order_id_key'), 'merchant_earnings', type_='unique')
    op.create_unique_constraint(None, 'merchant_earnings', ['order_id', 'kind'])
    # autogen 冗余:0001 基线已建过该索引,老库(stamp 到 0001)里已存在,幂等处理
    op.execute("CREATE INDEX IF NOT EXISTS ix_merchants_status ON merchants (status)")
    op.add_column('rider_earnings', sa.Column('kind', sa.Enum('earning', 'reversal', name='earning_kind', native_enum=False, length=24), nullable=False, server_default='earning'))
    op.add_column('rider_earnings', sa.Column('note', sa.String(length=200), nullable=False, server_default=''))
    op.drop_constraint(op.f('rider_earnings_order_id_key'), 'rider_earnings', type_='unique')
    op.create_unique_constraint(None, 'rider_earnings', ['order_id', 'kind'])
    op.add_column('withdrawals', sa.Column('paid_note', sa.String(length=200), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'paid_note')
    op.drop_constraint(None, 'rider_earnings', type_='unique')
    op.create_unique_constraint(op.f('rider_earnings_order_id_key'), 'rider_earnings', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('rider_earnings', 'note')
    op.drop_column('rider_earnings', 'kind')
    op.drop_index(op.f('ix_merchants_status'), table_name='merchants')
    op.drop_constraint(None, 'merchant_earnings', type_='unique')
    op.create_unique_constraint(op.f('merchant_earnings_order_id_key'), 'merchant_earnings', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('merchant_earnings', 'note')
    op.drop_column('merchant_earnings', 'kind')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
