"""license_image

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-16 18:13:14.779274
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 存量商家没有证照照片,置空串;新申请由接口强制必传
    op.add_column('merchants', sa.Column('license_image_url', sa.String(length=300), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'license_image_url')
    # ### end Alembic commands ###
