"""operations_pricing

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-16 18:30:06.995506
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('min_order_cents', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('merchants', sa.Column('packing_fee_cents', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('merchants', sa.Column('promo_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('orders', sa.Column('packing_fee_cents', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('discount_cents', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('subsidy_cents', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('promo_note', sa.String(length=100), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'promo_note')
    op.drop_column('orders', 'subsidy_cents')
    op.drop_column('orders', 'discount_cents')
    op.drop_column('orders', 'packing_fee_cents')
    op.drop_column('merchants', 'promo_rules')
    op.drop_column('merchants', 'packing_fee_cents')
    op.drop_column('merchants', 'min_order_cents')
    # ### end Alembic commands ###
