"""vouchers

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-16 19:22:40.110580
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('sell_price_cents', sa.Integer(), nullable=False),
    sa.Column('face_value_cents', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_merchant_id'), 'vouchers', ['merchant_id'], unique=False)
    op.create_table('voucher_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_no', sa.String(length=32), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sell_price_cents', sa.Integer(), nullable=False),
    sa.Column('face_value_cents', sa.Integer(), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=False),
    sa.Column('net_cents', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'paid', 'redeemed', 'refunded', 'cancelled', name='voucher_purchase_status', native_enum=False, length=24), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_purchases_code'), 'voucher_purchases', ['code'], unique=True)
    op.create_index(op.f('ix_voucher_purchases_customer_id'), 'voucher_purchases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_voucher_purchases_merchant_id'), 'voucher_purchases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_voucher_purchases_purchase_no'), 'voucher_purchases', ['purchase_no'], unique=True)
    op.create_index(op.f('ix_voucher_purchases_status'), 'voucher_purchases', ['status'], unique=False)
    op.create_index(op.f('ix_voucher_purchases_voucher_id'), 'voucher_purchases', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_purchases_voucher_id'), table_name='voucher_purchases')
    op.drop_index(op.f('ix_voucher_purchases_status'), table_name='voucher_purchases')
    op.drop_index(op.f('ix_voucher_purchases_purchase_no'), table_name='voucher_purchases')
    op.drop_index(op.f('ix_voucher_purchases_merchant_id'), table_name='voucher_purchases')
    op.drop_index(op.f('ix_voucher_purchases_customer_id'), table_name='voucher_purchases')
    op.drop_index(op.f('ix_voucher_purchases_code'), table_name='voucher_purchases')
    op.drop_table('voucher_purchases')
    op.drop_index(op.f('ix_vouchers_merchant_id'), table_name='vouchers')
    op.drop_table('vouchers')
    # ### end Alembic commands ###
