"""review_tags_flash_sale

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-17 12:26:53.991563
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('flash_price_cents', sa.Integer(), nullable=True))
    op.add_column('dishes', sa.Column('flash_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reviews', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'tags')
    op.drop_column('dishes', 'flash_until')
    op.drop_column('dishes', 'flash_price_cents')
    # ### end Alembic commands ###
