"""platform_ops

Revision ID: 0009
Revises: 0008
Create Date: 2026-07-17 12:39:06.080557
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_audience'), 'announcements', ['audience'], unique=False)
    op.create_table('app_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_events_event'), 'app_events', ['event'], unique=False)
    op.create_index(op.f('ix_app_events_user_id'), 'app_events', ['user_id'], unique=False)
    op.add_column('merchants', sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'photo_urls')
    op.drop_index(op.f('ix_app_events_user_id'), table_name='app_events')
    op.drop_index(op.f('ix_app_events_event'), table_name='app_events')
    op.drop_table('app_events')
    op.drop_index(op.f('ix_announcements_audience'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
