"""ledger anchors and witness nodes

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-17 13:51:29.502814
"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_anchors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day')
    )
    op.create_index(op.f('ix_ledger_anchors_chain_hash'), 'ledger_anchors', ['chain_hash'], unique=False)
    op.create_table('witness_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('verified_day', sa.String(length=10), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('divergent', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('heartbeats', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('witness_nodes')
    op.drop_index(op.f('ix_ledger_anchors_chain_hash'), table_name='ledger_anchors')
    op.drop_table('ledger_anchors')
    # ### end Alembic commands ###
